import { Profile } from "./types";

export const profiles: Profile[] = [
  {
    id: 1,
    name: "Donald Trump",
    email: "donaldtrump@gmail.com",
    percentage: 80,
    shortlisted: false,
    about: "Former US President, businessman, TV personality.",
    experience: "Real estate, business background.",
    hobbies: "Golf, social events, entertainment.",
    introduction: "Hello, I'm Donald Trump.",
    image: "/Trump.jpg",
    behaviour: 80,
    communication: 100,
    situation_handling: 40,
  },
  {
    id: 2,
    name: "Narendra Modi",
    email: "narendramodi@gmail.com",
    percentage: 82,
    shortlisted: false,
    about: "Prime Minister of India since 2014, focused on economic reforms, infrastructure.",
    experience: "Political, governance background.",
    hobbies: "Yoga, spirituality, nature.",
    introduction: "Namaste, I am Narendra Modi.",
    image: "/Modiji.jpg",
    behaviour: 60,
    communication: 40,
    situation_handling: 80,
  },
  {
    id: 3,
    name: "Mark Zuckerberg",
    email: "markzuckerberg@gmail.com",
    percentage: 58,
    shortlisted: false,
    about: "Co-founder, CEO of Meta Platforms (formerly Facebook), revolutionized social networking.",
    experience: "Expertise in technology, entrepreneurship, leadership.",
    hobbies: "Coding, tech exploration, family time.",
    introduction: "Hi, I'm Mark Zuckerberg.",
    image: "/Mark.jpg",
    behaviour: 90,
    communication: 100,
    situation_handling: 90,
  },
  {
    id: 4,
    name: "Elon Musk",
    email: "elonmusk@gmail.com",
    percentage: 73,
    shortlisted: false,
    about: "Entrepreneur, engineer, inventor in electric vehicles, space exploration.",
    experience: "Founder, leader of Tesla, SpaceX, Neuralink.",
    hobbies: "Sci-fi, gaming, family time.",
    introduction: "Hello, I'm Elon Musk.",
    image: "/Elon_Musk.jpg",
    behaviour: 60,
    communication: 70,
    situation_handling: 100,
  },
  {
    id: 5,
    name: "Bill Gates",
    email: "billgates@gmail.com",
    percentage: 65,
    shortlisted: false,
    about: "Co-founder of Microsoft, philanthropist addressing global health, poverty.",
    experience: "Computer science, business background.",
    hobbies: "Bridge, non-fiction, charity.",
    introduction: "Hi, I'm Bill Gates.",
    image: "/Bill_Gates.jpg",
    behaviour: 100,
    communication: 70,
    situation_handling: 80,
  },
  {
    id: 6,
    name: "Sundar Pichai",
    email: "sundar@gmail.com",
    percentage: 88,
    shortlisted: true,
    about: "CEO of Alphabet Inc. (Google's parent), driving growth, innovation in Google's products.",
    experience: "Engineering, management background.",
    hobbies: "Soccer, cuisine exploration, family time.",
    introduction: "Hello, I'm Sundar Pichai.",
    image: "/Sundar_Pichai.jpg",
    behaviour: 90,
    communication: 100,
    situation_handling: 100,
  },
];
